// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/debug/client-logs': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../build/debug/api/debug/client-logs/debug').default>>>>
    }
    '/trpc': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../build/trpc/trpc/trpc').default>>>>
    }
    '/': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../$vinxi/spa/client').default>>>>
    }
  }
}
export {}